[project]
name = "nmoya-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "humanize>=4.12.3",
    "pydantic>=2.11.5",
    "rich>=14.0.0",
    "toolz>=1.0.0",
    "tqdm>=4.67.1",
]
