name: Build and Deploy Zola Sites

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Zola
        run: |
          curl -sSL https://github.com/getzola/zola/releases/download/v0.20.0/zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv zola /usr/local/bin/zola

      - name: Build nikolasmoya_ssg
        run: |
          zola --root nikolasmoya_ssg build
          mkdir -p dist
          cp -r nikolasmoya_ssg/public/* dist/
          cp nikolasmoya_ssg/CNAME dist/ || true

      - name: Build iplayed_ssg
        run: |
          zola --root iplayed_ssg build
          mkdir -p dist/iplayed
          cp -r iplayed_ssg/public/* dist/iplayed/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
