name: Zola GH Actions config

on: 
 push:
  branches:
   - master

jobs:
  build:
    name: Build and push homepage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.20.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_DIR: nikolasmoya_ssg
        PAGES_BRANCH: gh-pages